[package]
name = "dll-proxy-macro"
edition = "2024"

[dependencies]
windows-sys = { version = "0.59", features = [
  "Win32_System_Com",
  "Win32_System_LibraryLoader",
  "Win32_UI_Shell",
] }

[features]
default = ["panic-handler"]
panic-handler = ["windows-sys/Win32_System_Threading"]

